export let EFFECTS_VALUES = {
  UP_DODGE: 20,
  UP_CRIT_DMG: 1.5,
  UP_CRIT: 25,
  POISON: 1,
  POISON_COEFF: 0.2,
  UP_AP: 5,
  DOWN_AP: 3,
  UP_AD: 5,
  DOWN_DODGE: 15,
  DOWN_SPEED: 10,
  DOWN_AD: 3
}

export let STACK_TYPES = {
  UP_DODGE: 'DURATION',
  UP_CRIT_DMG: 'DURATION',
  UP_CRIT: 'DURATION',
  POISON: 'INTENSITY',
  UP_AP: 'DURATION',
  DOWN_AP: 'DURATION',
  UP_AD: 'DURATION',
  DOWN_DODGE: 'DURATION',
  DOWN_SPEED: 'DURATION',
  DOWN_AD: 'DURATION',
  STUN: 'DURATION',
  TAUNT: 'DURATION'
}
export let EFFECT_TIMERS = {
  UP_DODGE: 3,
  UP_CRIT_DMG: 4,
  UP_CRIT: 4,
  POISON: 3,
  UP_AP: 3,
  DOWN_AP: 2,
  UP_AD: 3,
  DOWN_DODGE: 2,
  DOWN_SPEED: 1,
  DOWN_AD: 2,
  STUN: 2,
  TAUNT: 2
}
